version: '3'
services:
  parity:
    container_name: parity
    image: parity/parity:v2.1.4
    hostname: parity
    volumes:
      - ${PWD}/node-config:/config
      - ${PWD}/node-storage:/node-storage
    command: --config /config/config.toml --jsonrpc-cors all --jsonrpc-hosts all --unsafe-expose
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6545"]
      interval: 30s
      timeout: 10s
      retries: 5

  generator:
    build: ./generator/
    image: aeternity/initial-ae-balances-generator:${IMAGE_TAG-latest}
    hostname: generator
    depends_on:
      - parity
    links:
      - parity
    command: -p ws://parity:30303 -d 0
    volumes:
      - ${PWD}/output:/usr/src/code/output
